import {Doctor} from './doctor';
import {Patient} from './patient';
import {Treatment} from './treatment';
import {MedicalAdvice} from './medical-advice';
import {Disease} from './disease';

export class Diognes {

    public id: number;
    public date: string;
    public preature: string;
    public pulse: string;
    public temperature: string;
    public bMI: string;
    public gemeralApperance: string;
    public facialExpression: string;
    public painAssessment: string;
    public pallor: boolean;
    public cyanosis: boolean;
    public jaundice: boolean;
    public hairDistibution: boolean;
    public unexpectedBruise: boolean;
    public unexplainedBurn: boolean;
    public Scars: boolean;
    public veins: boolean;
    public stiffness: boolean;
    public thyroid: boolean;
    public lNodes: boolean;
    public headNeckOthers: string;
    public headSutures: string;
    public headFontanels: string;
    public expansion: boolean;
    public breathingSounds: boolean;
    public advSounds: boolean;
    public breast: string;
    public nippleDisgarge: boolean;
    public chestComments: string;
    public heartSounds: string;
    public murmurs: string;
    public heartOthers: string;
    public liver: string;
    public spleen: string;
    public kidneys: string;
    public ascites: boolean;
    public ascitesNote: string;
    public masses: boolean;
    public abdomenOthers: string;
    public extGenetalia: string;
    public upperLimdstremors: boolean;
    public upperLimdsclubbing: boolean;
    public upperLimdsjoints: string;
    public upperLimdsOthers: string;
    public lowerLimbsOdema: boolean;
    public lowerLimdsclubbing: boolean;
    public lowerLimdsjoints: string;
    public lowerLimdsOthers: string;
    public disabilitesMotor: boolean;
    public hearing: boolean;
    public visual: boolean;
    public mental: boolean;
    public psychic: boolean;
    public autism: boolean;
    public learningDisabilities: boolean;
    public possibleCause: string;
    public deformities: string;
    public neurologicalMotor: string;
    public neurologicalSensory: string;
    public neurologicalOthers: string;
    public eyesAcuityTR: string;
    public eyesAcuityTL: string;
    public eyesAcuityBR: string;
    public eyesAcuityBL: string;
    public eyesMovementR: string;
    public eyesMovementL: string;
    public eyesCorneaR: string;
    public eyesCorneaL: string;
    public eyesPupilR: string;
    public eyesPupilL: string;
    public eyesComment: string;
    public hearingR: string;
    public hearingL: string;
    public nose: boolean;
    public earDischargeR: string;
    public earDischargeL: string;
    public throat: boolean;
    public comments: string;
    public nutritionalRiskAssessment: boolean;
    public nutritionalRiskAssessmentComment: string;
    public functionalRehabilitationAssessmentN: boolean;
    public functionalRehabilitationAssessmentAp: boolean;
    public fallRiskAssessment: string;
    public riskForDM: boolean;
    public riskForHypertension: boolean;
    public riskForOthers: boolean;
    public riskForComments: boolean;
    public conclusion: string;
    public doctor: Doctor;
    public patient: Doctor;
    public  treaments: Treatment [];
    public medicalAdvicesList: MedicalAdvice [];
    public disease: Disease;
}
